from setuptools import setup, find_packages

setup(
    name="makarspace",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.20.0",
        "pandas>=1.3.0",
        "scikit-learn>=1.0.0",
        "torch>=1.9.0",
        "matplotlib>=3.4.0",
        "seaborn>=0.11.0",
        "streamlit>=1.10.0",
        "plotly>=5.5.0",
        "shap>=0.40.0",
        "lime>=0.2.0",
        "onnx>=1.10.0",
        "onnxruntime>=1.10.0",
        "fastapi>=0.75.0",
        "uvicorn>=0.17.0",
    ],
    extras_require={
        "dev": [
            "pytest>=6.0.0",
            "black>=22.1.0",
            "isort>=5.10.0",
            "mypy>=0.910",
            "flake8>=4.0.0",
        ],
    },
    author="MakarSpace Team",
    author_email="info@makarspace.org",
    description="AI-Driven Anomaly Detection for Spacecraft",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/makarspace/anomaly-detection",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    python_requires=">=3.8",
)
